"""Add house table

Revision ID: cc5ed79f88e8
Revises: 
Create Date: 2023-07-19 23:57:10.028812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cc5ed79f88e8"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "houses",
        sa.Column("id", sa.String(length=10), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=True),
        sa.Column("location", sa.String(length=128), nullable=False),
        sa.Column("region", sa.String(length=64), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("price", sa.String(length=16), nullable=False),
        sa.Column("bedrooms", sa.String(length=32), nullable=False),
        sa.Column("agent", sa.String(length=64), nullable=False),
        sa.Column("description", sa.String(length=512), nullable=False),
        sa.Column("sold", sa.String(length=4), nullable=False),
        sa.Column("datesold", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table("houses")
    # ### end Alembic commands ###
